name: prosegenerator_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - fastapi
      - uvicorn
      - openai==0.28
      - pinecone-client
      - sentence-transformers
      - torch
      - numpy
      - pydantic
